In [58]:
import numpy as np

def loadDataSet():
    postingList = [['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
                   ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
                   ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
                   ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
                   ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
                   ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]
    classVec = [0, 1, 0, 1, 0, 1]    #1 is abusive, 0 not
    return postingList, classVec

In [2]:
def createVocabList(dataSet):
    vocabSet = set([])  #create empty set
    for document in dataSet:
        vocabSet = vocabSet | set(document) #union of the two sets
    return list(vocabSet)

In [8]:
a = loadDataSet()

In [12]:
a[0]

[['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
 ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
 ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
 ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
 ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
 ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]

In [17]:
vaocabList = createVocabList(a[0])

In [24]:
def setOfWords2Vec(vocabList, inputSet):
    returnVec = [0]*len(vocabList)
    for word in inputSet:
        if word in vocabList:
            returnVec[vocabList.index(word)] = 1
        else: print("the word: %s is not in my Vocabulary!" % word)
    return returnVec

In [ ]:
P(w0 | c0) =>  给定是好文章，出现w0(dog)的概率。 =>  1/3

In [29]:
['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],

(['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],)

In [ ]:
P(w0 | c1) =>  给定是坏文章，出现w0(dog)的概率。 =>  2/3

In [ ]:
W => 

In [43]:
def trainNB0(trainMatrix, trainCategory):
    ## trainMatrix  
    numTrainDocs = len(trainMatrix) ## x 的 个数
    numWords = len(trainMatrix[0])  ## 向量长度
    
    pAbusive = sum(trainCategory)/float(numTrainDocs) # 0.5 直接算
    
    p0Num = np.ones(numWords); p1Num = np.ones(numWords)      #change to np.ones()
    
    p0Denom = 2.0; p1Denom = 2.0                              #change to 2.0
    
    
    for i in range(numTrainDocs):
        if trainCategory[i] == 1:  ## 坏
            p1Num += trainMatrix[i]
            print(p1Num)
            p1Denom += sum(trainMatrix[i])
            
        else:                     ## 好
            p0Num += trainMatrix[i]
            p0Denom += sum(trainMatrix[i])
    p1Vect = np.log(p1Num/p1Denom)          #change to np.log()
    p0Vect = np.log(p0Num/p0Denom)          #change to np.log()
    return p0Vect, p1Vect, pAbusive

In [44]:
listOPosts, listClasses = loadDataSet()
myVocabList = createVocabList(listOPosts)

trainMat = []
for postinDoc in listOPosts:
    trainMat.append(setOfWords2Vec(myVocabList, postinDoc))
    
    
    
p0V, p1V, pAb = trainNB0(np.array(trainMat), np.array(listClasses))
p0V

[2. 1. 1. 2. 1. 1. 2. 1. 1. 2. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 2.]
[2. 1. 1. 2. 2. 1. 3. 2. 2. 2. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 1. 1. 1. 2. 1. 1. 2.]
[2. 1. 1. 3. 2. 1. 4. 3. 2. 2. 2. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 2. 1.
 1. 1. 1. 2. 2. 2. 1. 2.]


array([-3.25809654, -2.56494936, -2.56494936, -2.56494936, -3.25809654,
       -2.56494936, -3.25809654, -3.25809654, -2.56494936, -3.25809654,
       -2.56494936, -2.56494936, -2.56494936, -2.56494936, -2.56494936,
       -2.15948425, -3.25809654, -2.56494936, -1.87180218, -2.56494936,
       -2.56494936, -2.56494936, -3.25809654, -2.56494936, -2.56494936,
       -2.56494936, -2.56494936, -3.25809654, -3.25809654, -3.25809654,
       -2.56494936, -3.25809654])

In [49]:
def classifyNB(vec2Classify, p0Vec, p1Vec, pClass1):
    print(vec2Classify)
    p1 = sum(vec2Classify * p1Vec) + np.log(pClass1)    #element-wise mult
    p0 = sum(vec2Classify * p0Vec) + np.log(1.0 - pClass1)
    if p1 > p0:
        return 1
    else:
        return 0

In [50]:
testEntry = ['love', 'my', 'dalmation']
thisDoc = np.array(setOfWords2Vec(myVocabList, testEntry))
print(testEntry, 'classified as: ', classifyNB(thisDoc, p0V, p1V, pAb))
testEntry = ['stupid', 'garbage']
thisDoc = np.array(setOfWords2Vec(myVocabList, testEntry))
print(testEntry, 'classified as: ', classifyNB(thisDoc, p0V, p1V, pAb))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0]
['love', 'my', 'dalmation'] classified as:  0
[0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
['stupid', 'garbage'] classified as:  1


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [56]:
np.log([2.71])

array([0.99694863])

In [57]:
TF, IDF..  stop words

SyntaxError: invalid syntax (3160933769.py, line 1)